name: Flutter Build APK --split-per-abi

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    env:
      FLUTTER_VERSION: "3.29.3"
      ANDROID_KEYSTORE_PATH: android/app/warehouse_amf-key.jks

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 20

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ~/.gradle
        key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-

    - name: Accept Android licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses


    - name: Debug keystore secret
      run: |
        echo "KEYSTORE_FILE secret: ${{ secrets.KEYSTORE_FILE }}"

    - name: Setup keystore from secrets
      run: |
        echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > ${{ env.ANDROID_KEYSTORE_PATH }}

    - name: Verify keystore file
      run: |
        keytool -list -v -keystore ${{ env.ANDROID_KEYSTORE_PATH }} -storepass ${{ secrets.KEYSTORE_PASSWORD }}


    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/keystore.properties
        echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/keystore.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/keystore.properties
        echo "storeFile=warehouse_amf-key.jks" >> android/keystore.properties
      shell: bash

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Build APK (release, split per ABI)
      run: flutter build apk --release --split-per-abi

    - name: Upload APKs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: build/app/outputs/flutter-apk/*.apk